name = "DeviceDispatcher"
uuid = "eca884f9-ffb1-4503-8015-63efe720ef55"
license = "MIT"
authors = ["Lukas Yoder <packages@lukasyoder.dev>"]
description = "Dynamic CPU ⇄ GPU data-movement helper for heterogeneous computing that auto-detects CUDA, AMDGPU, Metal, or oneAPI back-ends and lets you switch devices in one line or one macro."
version = "1.0.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
DeviceDispatcherAMDGPUExt = "AMDGPU"
DeviceDispatcherCUDAExt = "CUDA"
DeviceDispatcherMetalExt = "Metal"
DeviceDispatcherOneAPIExt = "oneAPI"

[compat]
AMDGPU = "1.3.6"
Adapt = "4.3.0"
CUDA = "5.8.2"
Documenter = "1.14.1"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
Metal = "1.6.3"
Random = "1.11.0"
Test = "1.11.0"
julia = "1.11.5"
oneAPI = "2.0.3"
